### PR TITLE
feature: isfaq.html - add info about UTF-8 BOM 

### PR DESCRIPTION
**Pull request by tomina-s**
this FAQ problem described in this stackoverflow question: https://stackoverflow.com/questions/49922735/inno-setup-unicode-encoding-issue-with-messages-in-iss-script

### CODE REVIEW

**Comment by tomina-s** [comment]
@martijnlaan hello,
do you have any updates on the PR?

**Comment by tomina-s** [comment]
@martijnlaan ping

**Comment by martijnlaan** [comment]
I've added a note to the help file. See https://github.com/jrsoftware/issrc/commit/13b5469ce73298488a4be8bf159f098ecefa0d31

**Comment by martijnlaan** [comment]
FWIW, I noticed the requirement was actually already documented in the help file in both the [Creating Installations](https://jrsoftware.org/ishelp/index.php?topic=creatinginstallations) and the [Script Format Overview](https://jrsoftware.org/ishelp/index.php?topic=scriptformatoverview) topics. However, I'm working on removing the requirement.

**Comment by tomina-s** [comment]
yes, now I see this information in the documentation, and even a Google search gives links to these documentation pages.

in the meantime, this edit will be in place, as you did, on the [Unicode Inno Setup](https://jrsoftware.org/ishelp/index.php?topic=unicode) page 

okay, good luck with the new release

**Pull request closed without merging**
